source 'https://github.com/CocoaPods/Specs.git'

#修改为项目依赖方式
install! 'cocoapods', :generate_multiple_pod_projects => true
# 忽略引入库的所有警告
inhibit_all_warnings!

# 部署目标
deployment_target = '12.0'
platform :ios, deployment_target

target 'KWOC' do

use_frameworks!

  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
  
  pod 'HandyJSON'
  
  pod 'TZImagePickerController'
  
  pod 'MBProgressHUD'
  
  pod 'SDWebImage'
  
  pod 'SnapKit'
  pod 'Masonry'
	
end



# 修改三方库最低部署目标
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |bc|
            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
